# Generated by Django 4.1.3 on 2022-11-22 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='prix_produit',
            field=models.DecimalField(decimal_places=0, max_digits=20),
        ),
    ]
